### PR TITLE
Adds russian lang

### PR DESCRIPTION
**Pull request by maxx0n**
Adds ru/ folder with index.md file as a start point for translation process to russian

### CODE REVIEW

**Comment by maxx0n** [comment]
Hi, i added russian version of the site. Can you approve this changes?

**Comment by jgkim** [comment]
@maxx0n Thank you for the request. I will look into it and merge it soon!

**Comment by maxx0n** [comment]
russian version lives here http://maxx0n.github.io/ru/. It works without CNAME on GitHub Pages=)
I've fixed marked lines

**Comment by jgkim** [comment]
@maxx0n I know it works on your own domain name, but if I merge this, it will break http://5stardata.info. That's why I suggested running Jekyll on your own machine. Could you add back `CNAME`?

**Comment by maxx0n** [comment]
added

**Comment by jgkim** [comment]
@maxx0n Thank you for your effort. :)

**Comment by maxx0n** [comment]
thank you for your help 2 =) it's a great initiative

**Pull request merged**
