### PR TITLE
Fixed mistake calling Excel an "open format" and added reference to ODS

### PR DESCRIPTION
**Pull request by giacecco**
Hi @mhausenblas, it's all in the title, hope it's useful.

### CODE REVIEW

**Comment by jgkim** [comment]
Hi @giacecco, this issue has already discussed in https://github.com/mhausenblas/5stardata.info/pull/17. What do you think about @davetaz's opinion?

**Comment by giacecco** [comment]
Ha! Good ol' @davetaz. I guess it is all about who is privileged enough to know Tim and what he meant in the first place, and Dave is. 

Looking at what he writes, I believe that there are two points here:
- ODS is an open format but (unfortunately) it's a niche one, too. Because of that, attributing an extra star to data in ODS format does not really feel right. I agree, and my proposed https://github.com/Digital-Contraptions-Imaginarium/5stardata.info/commit/857b80122819001243e34eded13c1494de60db4c can be dropped.
- It is still unclear what the 3 stars means in the end. Dave describes the root cause of the misunderstanding when he says: - _There has been a major mis-interpretation of the 3rd star that it can be done instead of the the second as opposed to in addition to_. But which is Tim's intended definition then?

What is wrong perhaps is the 1 to 5 progression of the stars, as if it was a level you achieve, rather than a score. We should rather write the stars model as:
- you gain 1 star if you make your stuff available on the Web (whatever format) _and_ under an open license
- you gain 1 star if you make it available as structured data (e.g., Excel instead of image scan of a table), _even if not under an open licence_
- you gain 1 star if you make it available in a _mainstream_ non-proprietary open format (e.g., CSV) _even if it is not structured_
- you gain 1 star if you use URIs to denote things, so that people can point at your stuff 
- etc. etc.

Really, only someone who was there when the model was define knows. Today what's on the website simply looks like an error.

**Comment by davetaz** [comment]
You have to be careful here too, gaining the top 4 stars doesn't make your data usable unless it is licensed as such, so the language "you gain" is not great. 
- You obtain the first star for publishing "stuff" under and open licence.
- You can achieve the second star if this stuff is usable as well as open.
- You can move to the third star if you have done the first two AND also published your data in an open format that has an open specification. 
- You can add the fourth star if the things you describe use web based identifiers so people can click on them to find out what they are.
- You achieve the fifth and top star if and only if you have done all four previous stars and then link to other peoples stuff to create a web of data.

**Comment by giacecco** [comment]
Mmmh so now it looks very explicit that the stars are "levels" and not a score, so you can gain the nth level only after you gained the n-1th level, that is how I always interpreted that, the way it looks like from the graphics on the website, and also the way I feel more comfortable with.

**BUT** there remains the ambiguity around the third star. Why "CSV as well as of Excel"? If one is aiming at the 3rd star she's already achieved the 2nd star where Excel suffices, so it should be "CSV _rather than_ Excel".

On a side note, you switched from the "structured" to "usable" term, that's dangerous... :-)

**Pull request closed without merging**
